"""added followers relationship table

Revision ID: 890c2c987610
Revises: b001ff1a1451
Create Date: 2018-04-26 15:19:32.684761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890c2c987610'
down_revision = 'b001ff1a1451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
